Know-Nepal/tech-companies

data/companies.json
Added the company "**Lanceme Up**"
NOTE: _Added Lanceme UP before Leapfrog to sort by company name_
=> feat: Add "Lanceme Up"

.github/ISSUE_TEMPLATES/bug_report.md, .github/ISSUE_TEMPLATES/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Added templates for issues (feature request and bug report) and pull requests, so that users can find it easy to contribute 🙏
=> chore: added template file for PR and issue

data/companies.json
=> feat: add `COTIVITI NEPAL`

data/companies.json
=> add vrit tech

data/companies.json
F1Soft International Company Information
=> Added F1Soft International

data/companies.json
Added major cybersecurity companies from Nepal :)
=> added major cybersecurity companies from Nepal

data/companies.json
Just added one new company in the list
=> Added company Tekvortex in the list

.github/workflows/auto_comment.yml
This change will auto comment on PRs merged with a `Thank you` message and a link to join our Discord Server.
N/a
=> feat: add a auto-comment workflow

data/intopros-technologies.json
=> feat: Add Intopros technologies

.github/workflows/auto_comment.yml
=> chore: Fix auto comment workflow

data/idea-breed-technology.json
The PR introduces a new company called Idea breed in the data folder.
Created a new JSON file and added detail of the company inside it using the data format specified.
=> add idea breed technology company

CONTRIBUTING.md, data/cotiviti-nepal.json, data/cryptogen-nepal.json, data/eminance-ways.json, data/f1soft-international.json, data/fusemachines.json, data/idea-breed-technology.json, data/intopros-technologies.json, data/lanceme-up.json, data/leapfrog-technology.json, data/tekvortex.json, data/vairav-technology.json, data/vrit-technologies.json
Fixes #9 
Users could always check the company website and then find the contact details, but having them directly in the data files would reduce 1 additional step the users would have to take.
=> feat: Add email and phone for all companies

data/yarsa-labs.json
N/A
Couldn't find their email though!
=> feat: add `Yarsa Labs`

data/fusemachines.json, data/growbydata.json
=> Add GrowByData Services Pvt. Ltd.

data/logpoint-nepal.json
* Added insta-tag link in `instagram` key. 
* `establishedAt` information from : https://www.logpoint.com/en/history-of-logpoint/
=> Add logpoint nepal

data/cedar-gate-nepal.json
The company `Cedar Gate Technologies` is known to be `Cedar Gate Services Pvt Ltd` in nepal. Updated accordingly.
=> Add CedarGate Technologies i.e. CedarGate Services pvt. ltd. in nepal

data/cloudfactory.json
I have added Cloudfactory information.
=> Add cloudfactory information

data/crystal-infosys.json
=> feat: add `Crystal Infosys`

data/f1soft-international.json
- ✔ Documentation change
To have all the data related to the company.
- Added YouTube Channel Link
=> F1softInternational YouTube Channel Link Added!

data/bajra-technologies.json, data/cedar-gate-nepal.json, data/growbydata.json, data/logpoint-nepal.json, data/prixa-tech.json
Established Date as per : https://www.lusha.com/business/e4e9c060fb156533/
=> Add bajra-technologies

data/vrit-technologies.json
=> update vrit tech yt channel

data/tech-sanjal.json
=> feat: add Tech sanjal

data/werkk.json
Added a New Company: [werkk freelancing platform](http://werkk.tech/)
=> added werkk freelancing platform

data/ekbana-solutions.json
=> Added: Ekbana Solutions

data/ekbana-solutions.json, data/ninja-infosys.json
=> add new tech compony in Nepalgunj, Named Ninja Infosys

data/eastern-hawk.json
Added Eastern Hawk Solutions Pvt. Ltd. from eastern nepal to the list of tech companies.
=> feat: add eastern hawk solutions

data/info-developers.json
=> feat: add info-developers.json

data/luminr-co.json
=> Add Luminr.co in JSON fromat

data/digi-technology.json
=> feat: added digi technology

data/companies.json
=> added alpas

data/companies.json
Fixes #67
I couldn't find some of the companies in the third-party dataset of registered companies.
Also I have converted two dates into proper format.
=> Update established date.

data/companies.json
=> Added Dolphin Dive Technology

data/companies.json
Two companies are added in the data file.
=> Added Adex Ltd. and NAXA

data/companies.json
=> feat: add TechLekh website

data/companies.json
Added some tech companies starting from the alphabet: `a`.
=> Add companies starting from alphabet "a"

data/companies.json
=> feat: add verisk nepal pvt ltd.

data/companies.json
=> feat: add Tech Sathi website

data/companies.json
=> add hazesoft

data/companies.json
=> Added YCO Pvt. Ltd.

data/companies.json
=> chore: fixed the trailing comma error in yco pvt. ltd.

data/companies.json
=> feat: add genese solution

data/companies.json
=> Added TAI Inc.

data/companies.json
This PR edits all the phone numbers in proper format as per [CONTRIBUTING.md](https://github.com/Know-Nepal/tech-companies/blob/main/CONTRIBUTING.md)
=> feat: update phone numbers according to format

data/companies.json
=> Vertex Web Surf  added 

data/companies.json
=> feat: add braindigit IT solution

data/companies.json
=> fix the phone number format

data/companies.json
=> added new company "clusus" to companies.json

data/companies.json
=> feat: add NepalLink Network

.github/CODEOWNERS, data/companies.json
Added information about e-Zone International company.
=> E zone international

data/companies.json
Added BlackBox Technologies Pvt. Ltd. to the companies.json and it's details
=> Added A Company: BlackBox Technologies
